name: Stats

on:
  schedule:
    - cron: '0 8 * * *'
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: 
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          
      - name: Run Python script
        run: python stats.py

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update stats
          commit_user_name: rosendocamal [GitHub Actions]
          commit_author: rosendocamal
